name: PythonCiCd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
      - name: deploy
        run: make deploy

      - name: Build status badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: ${{ matrix.os }}, ${{ matrix.python-version}}
          LABEL: ${{ matrix.os }}, ${{ matrix.python-version}}
          STATUS: ${{ job.status }}
          COLOR: ${{ job.status == 'success' && 'green' || job.status == 'failure' && 'red' || 'yellow' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
