name: PythonCiCd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.7
            name: ubuntu_latest_Python_3_7
          - os: ubuntu-latest
            python-version: 3.8
            name: ubuntu_latest_Python_3_8
          - os: ubuntu-latest
            python-version: 3.9
            name: ubuntu_latest_Python_3_9
          - os: ubuntu-18.04
            python-version: 3.7
            name: ubuntu_18_04_Python_3_7
          - os: ubuntu-18.04
            python-version: 3.8
            name: ubuntu_18_04_Python_3_8
          - os: ubuntu-18.04
            python-version: 3.9
            name: ubuntu_18_04_Python_3_9
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
      - name: deploy
        run: make deploy

      - name: Build status badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: ${{ matrix.name }}
          LABEL: ${{ matrix.name }}
          STATUS: ${{ job.status }}
          COLOR: ${{ job.status == 'success' && 'green' || job.status == 'failure' && 'red' || 'yellow' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
